apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: kafka-ui
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-02-22T20:30:20Z"
  finalizers:
  - gke.networking.io/l4-netlb-v1
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/version: v0.7.2
    helm.sh/chart: kafka-ui-0.7.6
  name: kafka-ui
  namespace: default
  resourceVersion: "1771793674648799001"
  uid: 13464cad-e907-482c-9808-063f8f15d13f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.230.110
  clusterIPs:
  - 34.118.230.110
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30790
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/name: kafka-ui
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.185.204.178
      ipMode: VIP
