apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2026-02-22T23:41:21Z"
  finalizers:
  - gke.networking.io/l4-netlb-v1
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: default
  resourceVersion: "1771803711904287013"
  uid: e7ec24fe-f7b8-49d9-ad6f-525d752a05d2
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.229.87
  clusterIPs:
  - 34.118.229.87
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31879
    port: 80
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.179.129.157
      ipMode: VIP
