apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: kafka-operator
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-02-22T20:22:05Z"
  generation: 1
  labels:
    app: strimzi
    app.kubernetes.io/managed-by: Helm
    chart: strimzi-kafka-operator-0.50.1
    component: deployment
    heritage: Helm
    release: kafka-operator
  name: strimzi-cluster-operator
  namespace: default
  resourceVersion: "1771791766913887003"
  uid: 30a2c8db-a0a4-475c-a8a7-a422ea1897e8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      containers:
      - args:
        - /opt/strimzi/bin/cluster_operator_run.sh
        env:
        - name: STRIMZI_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: STRIMZI_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
          value: quay.io/strimzi/kafka:0.50.1-kafka-4.1.1
        - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
          value: quay.io/strimzi/kafka:0.50.1-kafka-4.1.1
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            4.0.0=quay.io/strimzi/kafka:0.50.1-kafka-4.0.0
            4.0.1=quay.io/strimzi/kafka:0.50.1-kafka-4.0.1
            4.1.0=quay.io/strimzi/kafka:0.50.1-kafka-4.1.0
            4.1.1=quay.io/strimzi/kafka:0.50.1-kafka-4.1.1
        - name: STRIMZI_KAFKA_CONNECT_IMAGES
          value: |
            4.0.0=quay.io/strimzi/kafka:0.50.1-kafka-4.0.0
            4.0.1=quay.io/strimzi/kafka:0.50.1-kafka-4.0.1
            4.1.0=quay.io/strimzi/kafka:0.50.1-kafka-4.1.0
            4.1.1=quay.io/strimzi/kafka:0.50.1-kafka-4.1.1
        - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
          value: |
            4.0.0=quay.io/strimzi/kafka:0.50.1-kafka-4.0.0
            4.0.1=quay.io/strimzi/kafka:0.50.1-kafka-4.0.1
            4.1.0=quay.io/strimzi/kafka:0.50.1-kafka-4.1.0
            4.1.1=quay.io/strimzi/kafka:0.50.1-kafka-4.1.1
        - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: quay.io/strimzi/operator:0.50.1
        - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
          value: quay.io/strimzi/operator:0.50.1
        - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
          value: quay.io/strimzi/operator:0.50.1
        - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
          value: quay.io/strimzi/kafka-bridge:0.33.1
        - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
          value: quay.io/strimzi/kaniko-executor:0.50.1
        - name: STRIMZI_DEFAULT_BUILDAH_IMAGE
          value: quay.io/strimzi/buildah:0.50.1
        - name: STRIMZI_DEFAULT_MAVEN_BUILDER
          value: quay.io/strimzi/maven-builder:0.50.1
        - name: STRIMZI_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: STRIMZI_FEATURE_GATES
        - name: STRIMZI_LEADER_ELECTION_ENABLED
          value: "true"
        - name: STRIMZI_LEADER_ELECTION_LEASE_NAME
          value: strimzi-cluster-operator
        - name: STRIMZI_LEADER_ELECTION_LEASE_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: STRIMZI_LEADER_ELECTION_IDENTITY
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: quay.io/strimzi/operator:0.50.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthy
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: strimzi-cluster-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 384Mi
          requests:
            cpu: 200m
            memory: 384Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: strimzi-tmp
        - mountPath: /opt/strimzi/custom-config/
          name: co-config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: strimzi-cluster-operator
      serviceAccountName: strimzi-cluster-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 1Mi
        name: strimzi-tmp
      - configMap:
          defaultMode: 420
          name: strimzi-cluster-operator
        name: co-config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-02-22T20:22:46Z"
    lastUpdateTime: "2026-02-22T20:22:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-02-22T20:22:05Z"
    lastUpdateTime: "2026-02-22T20:22:46Z"
    message: ReplicaSet "strimzi-cluster-operator-57bbf65d68" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
